#+TITLE: Coquitlam

Lets plan how to get Coquitlam (and the whole Tri-Cities) to Zero
Emissions.

I need a better name for this...
  - Dignity
  - Excursion
  - Imagination
  - Reverie
  - Concept
  - Contemplation
  - Epiphany
  - Insight
  - Utopia
  - Luster, Sparkle, Shine, 
  - Revenant
  - Return
  - Rise/Legacy
  - Accord
  - Harmony

(It might be easier to frame this as coming back to what was, rather than bolding seeking what is new).
 
Also, what's the region to target?
  - Tri Cities I think... as Erik said, it's surrounded by natural features.


Our history is a mill... before WW2 (and before Lougheed highway) it would have been more inward focused.

* History

Coquitlam
By 1908, a mill town of 20 houses, a store, post office, hospital, office block, barber shop, pool hall and a Sikh temple[6] had grown around the mill. 

Port Coquitlam
Was originally farming.
A major impetus to the creation of a municipality was when the Canadian Pacific Railway moved its freight terminus from Vancouver to "Westminster Junction", building a spur line to the Fraser River port of New Westminster in 1911.

Port Moody
Was originally a military fort.

Had a train line and boom followed by Bust as the train went to
Vancouver. 

The railway was completed with the last spike driven at Craigellachie
on November 7, 1885 and a train arriving at Port Moody the next
day. The first scheduled passenger transcontinental train arrived on
July 4, 1886, a date which is still celebrated during Golden Spike
Days. Real estate prices soared, but soon fell flat when a branch line
was built to Vancouver in 1887.

While many people lost a great deal of money and moved on, others,
including real estate tycoon and ship captain, James A. Clarke, and
several lumber mills, decided to remain. On April 7, 1913, Port
Moody's Council met for the first time as a city.


* Is there anything in History to use?

I'd like to present it as a return... one could say that we're
historically mills... but then eclipsed by Vancouver.

We'd be returning to the frontier spirit... blazing a new trail.

Tri-Cities Frontier Proposal

As rugged individuals against a harsh nature, we're recovering the
pride of our ancestry and history and building an integrated
Tri-Cities that is Green.

Need some narratives here... about people and the changes they are
making...

* Radio Station: 98.7 The Point

98.7 radio station -- the Point.

* What Goes into this Plan?

A vision for the next many years.

 - Integrating the City to reduce driving
 - A transit plan
 - Energy efficiency measures
 - Zoning changes to encourage densification
 - Green Spaces and stuff like that
 - Ammenities, social housing, etc,
 - Resilency via local committee efforts.
 - ELECTRIFIED CITY FLEET (They spend 3,870,000 per year on fleet capital).

More ideas:

 - Tech incubator for green tech (e.g. mist showers)
 - Living wage regulation -- so Coq businesses must pay at least enough so that there
   workers can afford the live in Coq?
 - Buyback of abandoned homes. Convert to neighborhood green spaces.
   (About $12 million a year is spent buying parklands... so that's like twelve houses ;-)
   But why should some private individual make a million dollars on an abandoned home?
 - Covered side walks (e.g. by trees) wider sidewalks.
   (Bicycle/Greenway Facilities Program in Coquitlam?)
 - Zoning changes.
 - Promoting eat local, buy local?
 - Raise money via 'Bonds' -- city debt owned to city citizens and repayed to them,
   rather than to banks.
 - Why are libraries public but gyms private?  Why are roads public
   but telecommunications private?  Why are buses public but taxis
   private?

Civic facilities are expensive... are they necessary? Is there a small
sort of thing that could be done?  Like turning houses into libraries?
Or library depots or something?

* Where will the money come from?

I've started looking at the budget...

A few things:
 - Do we have a problem with extractive rents? (e.g. companies that work here, but funnel
   profits far out of the community? -- like people buying from Amazon)
 - Can we make 'lateral' transfers?  Higher taxes that support services that lower cost of living
   by an eqivalent amount?
 - Are we charging a fair amount for taxes?  Are some groups getting an superb deal?

 - If any groups are not expected to pay property taxes, are they providing some other social
   benefit?

 - Why does it cost so much to develop a park?  What are we talking about here?  Can we do
   cheaper parks -- just let nature grow?   How about these sports facilities -- important,
   do we have enough or too many?  Should they be centralized like this, or more dispersed?

 - We shouldn't be afraid of having common property that eliminates some private businesses.
   E.g. libraries, public gyms.  Having these things can make good sense (case by case). Lower cost of
   living, and more integrated communities.  Is there a good rubric for deciding what things are
   best public and what things are best private?   E.g. why are libraries public but gyms are not?
   Why are roads public but telecommunications private?  Why are buses public but taxis private?


* Publishing

** Website

I think I'll just publish my DEFT collection as a project. Then it'll
be up to date most of the time. Put a GIT repo on it and others can
access it if they want too.

** Reports

Reports are harder. I like latex, but others probably don't so much.  Still,
for what we're trying to do it might be valuable.

** Presentations

Harder still. Latex presentations are not wonderful and not interactive... might
want to look at one of those website based presentation tools.

reveal.js looks great.
impress.js and hovercraft look great...

How do newspapers do those interactive things?  It's called 'storytelling'.
Google javascript storytelling library.

https://geoviz.ceoas.oregonstate.edu/storymap/

https://pudding.cool/process/how-to-implement-scrollytelling/demo/waypoints/

https://pudding.cool/process/how-to-implement-scrollytelling/

This one recommends a 'stepper'.
https://eagereyes.org/blog/2016/the-scrollytelling-scourge

** Videos

To be determined.
