#+TITLE: Coquitlam

Lets plan how to get Coquitlam (and the whole Tri-Cities) to Zero
Emissions.

See [[file:budgets.org][Budgets]].

I need a better name for this...
  - Dignity
  - Excursion
  - Imagination
  - Reverie
  - Concept
  - Contemplation
  - Epiphany
  - Insight
  - Utopia
  - Luster, Sparkle, Shine, 
  - Revenant
  - Return
  - Rise/Legacy
  - Accord
  - Harmony

(It might be easier to frame this as coming back to what was, rather than bolding seeking what is new).
 
Also, what's the region to target?
  - Tri Cities I think... as Erik said, it's surrounded by natural features.


Our history is a mill... before WW2 (and before Lougheed highway) it would have been more inward focused.

* Test Index
  #+INDEX: test

This is a test index entry...

* History


Coquitlam
By 1908, a mill town of 20 houses, a store, post office, hospital, office block, barber shop, pool hall and a Sikh temple[6] had grown around the mill. 

Port Coquitlam
Was originally farming.
A major impetus to the creation of a municipality was when the Canadian Pacific Railway moved its freight terminus from Vancouver to "Westminster Junction", building a spur line to the Fraser River port of New Westminster in 1911.

Port Moody
Was originally a military fort.

Had a train line and boom followed by Bust as the train went to
Vancouver. 

The railway was completed with the last spike driven at Craigellachie
on November 7, 1885 and a train arriving at Port Moody the next
day. The first scheduled passenger transcontinental train arrived on
July 4, 1886, a date which is still celebrated during Golden Spike
Days. Real estate prices soared, but soon fell flat when a branch line
was built to Vancouver in 1887.

While many people lost a great deal of money and moved on, others,
including real estate tycoon and ship captain, James A. Clarke, and
several lumber mills, decided to remain. On April 7, 1913, Port
Moody's Council met for the first time as a city.

