#+TITLE: The Problem

I think a story could be told around the scale of the
problem... breaking it down into the sub parts...

https://www.bcemissions.ca/go/city/Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Moody/index.html

The above is a good starting point. Basically, I want to get the data
on the populations (because per-capita is important).

I also want to demonstrate land use, because this is the range of
options we have for local food, expansion, etc.

Then, breakdown into housing types.. because they have different energy profiles.
 - Should be able to get exact numbers for this.

Then, lets talk about the heating and electricity used... this varies with housing type.
 - I can really only get BC averages for this.  That's probably reasonable. I don't think
   any of the tri-cities is significantly better/worse efficiency ratings for houses than other places
   in BC.
 - This leads to an option for exploration -- what if we could change our housing profile?

Then, commutes... what type, how far.
 - Can't seem to get exact numbers -- have to let the user decide if we're more
   like Vancouver, or more like Mission.
 - This leads to an option -- what if we could increase the number of people living AND working in 
   tri-cities.... 

Then solid waste
  - CO2 produced... what about the cost of transporting it?  How much is compost and where does that go?
  - What about human body waste -- e.g. sewage... does this produce CO2?  What do we do with it at treatment?

Then air quality
  - How is our air?
  - What happens if we have more electric cars or walking?

* Populations

https://www2.gov.bc.ca/gov/content/data/statistics/people-population-community/population

| *Census Area*   | *Year* | *Count* |
|-----------------+--------+---------|
| Burnaby         |   2018 |   98789 |
| Coquitlam       |   2018 |   96700 |
| Maple Ridge     |   2018 |   43469 |
| New Westminster |   2018 |   35746 |
| Mission         |   2018 |   17627 |

Source: Prepared by BC Stats, Ministry of Technology, Innovation and Citizens' Services

* Land Use

Agricultural Land Reserve
https://www.alc.gov.bc.ca/alc/content/alr-maps/maps-and-gis



* Commuting


Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Lp-eng.cfm

In the long form, there is information about journey to work.

98-400-X2016324 Mode, Duration, Exit Time, 
98-400-X2016328 Mode, Duration, Distance, Exit Time
98-400-X2016329 Destination, Mode   (Distination measures -- same census subdivision? same census division? same province?)
98-400-X2016334 Mode, Industry

I think if I sort of 'blend' the profiles for Vancouver and Mission/Abbotsford I can come up with some kind of reasonable guess.  This would have to be a slider.

'Assuming Tri-Cities are more like Vancouver --- More like Abbotsford'

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm


He showed it as a commute distance chart... 
This data also varies with time... 2006 and 2016 we have.

They also showed a chart of commute modes.




* Housing types

Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Lp-eng.cfm

Source 1 is 98-400-X2016017 - Structural type by household size
Source 2 is 98-400-X2016015 - Structural type by age and sex.
(there are also some income related ones broken out this way).

# Output the table... Sort so the total is last.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)

  df <- read.table(unz("../census2016/98-400-X2016017_ENG_CSV.ZIP", "98-400-X2016017_English_CSV_data.csv"), header=T, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              'Belcarra, VL',
              'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Structural.type.of.dwelling..10.,
             Dim..Household.size..8...Member.ID...1...Total...Household.size,
             Dim..Household.size..8...Member.ID...2...1.person,
             Dim..Household.size..8...Member.ID...3...2.persons,
             Dim..Household.size..8...Member.ID...4...3.persons,
             Dim..Household.size..8...Member.ID...5...4.persons,
             Dim..Household.size..8...Member.ID...6...5.or.more.persons,
             Dim..Household.size..8...Member.ID...7...Number.of.persons.in.private.households,
             Dim..Household.size..8...Member.ID...8...Average.household.size)

  names(df) <- c('city', 'type', 'total.houses',
		 '1.person',
		 '2.persons',
		 '3.persons',
		 '4.persons',
		 '5.or.more.persons',
		 'total.persons',
		 'avergae.household.size')

  options(width=300)
  df
#+end_src

It looks like a lot of single family detached homes have just 1 or 2 people.


** Old housing types data

You can also get it from this data viewer:
https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dv-vd/cpdv-vdpr/index-eng.cfm
Census Program Data Viewer, 2016 Census


Then focus on coquitlam and add comparisons to the other cities...

| *City*         | *Single-detached home* | *Aps* | *Apt 5-* | *Apt Duplex or Flat* | *Apt 5+* |
|----------------+------------------------+-------+----------+----------------------+----------|
| Coquitlam      |                   38.5 |  48.3 |     22.2 |                 14.6 |     11.5 |
| Port Moody     |                   30.3 |  46.1 |     22.9 |                  8.5 |     14.7 |
| Port Coquitlam |                   38.5 |  42.7 |     25.1 |                 16.6 |        1 |
| Anmore         |                   70.8 |  14.6 |        0 |                 14.6 |        0 |

| *City*         | *Carpool* | *Public Transit* | *Active Transit* | *Car* |
|----------------+-----------+------------------+------------------+-------|
| Coquitlam      |      12.4 |             17.9 |              4.3 |  65.4 |
| Port Moody     |      10.8 |             16.9 |              3.6 |  68.7 |
| Port Coquitlam |      13.2 |             12.6 |              3.7 |  70.5 |
| Anmore         |      10.8 |              7.7 |              1.4 |  80.1 |

| *City*         | *Avg Commute* |
|----------------+---------------|
| Coquitlam      |          33.8 |
| Port Moody     |            34 |
| Port Coquitlam |          32.6 |
| Anmore         |          32.5 |



   
https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Ap-eng.cfm?LANG=E&APATH=3&DETAIL=0&DIM=0&FL=A&FREE=0&GC=0&GID=0&GK=0&GRP=1&PID=109534&PRID=10&PTYPE=109445&S=0&SHOWALL=0&SUB=0&Temporal=2016&THEME=116&VID=0&VNAMEE=&VNAMEF=

** COQUITLAM

https://www.coquitlam.ca/planning-and-development/resources/community-profiles-demographics/census.aspx

The XLS file has 'households'.

| *Type*                                                     |       |
|------------------------------------------------------------+-------|
| Single-detached house                                      | 19785 |
|------------------------------------------------------------+-------|
| Apartment in a building that has five or more storeys      |  5915 |
|------------------------------------------------------------+-------|
| Other attached dwelling                                    | 25380 |
| + Semi-detached house                                      |  1590 |
| + Row house                                                |  4910 |
| + Apartment or flat in a duplex                            |  7480 |
| + Apartment in a building that has fewer than five storeys | 11380 |
| + Other single-attached house                              |    15 |
|------------------------------------------------------------+-------|
| Movable dwelling                                           |   250 |


* Heating and Electricity
Residential
Commercial Small/Medium
Large Industrial
Wholesale?

(For categories, Elec, Natural Gas, Heating Oil, Propane)

http://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/comprehensive_tables/list.cfm

* Solid Waste

They explained solid waste produced and the CO2 generated from that solid waste.

* Air Quality

They showed fine particulate matter.
