#+TITLE: The Problem

I think a story could be told around the scale of the
problem... breaking it down into the sub parts...

https://www.bcemissions.ca/go/city/Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Moody/index.html

The above is a good starting point. Basically, I want to get the data
on the populations (because per-capita is important).

I also want to demonstrate land use, because this is the range of
options we have for local food, expansion, etc.

Then, breakdown into housing types.. because they have different energy profiles.
 - Should be able to get exact numbers for this.

Then, lets talk about the heating and electricity used... this varies with housing type.
 - I can really only get BC averages for this.  That's probably reasonable. I don't think
   any of the tri-cities is significantly better/worse efficiency ratings for houses than other places
   in BC.
 - This leads to an option for exploration -- what if we could change our housing profile?

Then, commutes... what type, how far.
 - Can't seem to get exact numbers -- have to let the user decide if we're more
   like Vancouver, or more like Mission.
 - This leads to an option -- what if we could increase the number of people living AND working in 
   tri-cities.... 

Then solid waste
  - CO2 produced... what about the cost of transporting it?  How much is compost and where does that go?
  - What about human body waste -- e.g. sewage... does this produce CO2?  What do we do with it at treatment?

Then air quality
  - How is our air?
  - What happens if we have more electric cars or walking?

* Populations

https://www2.gov.bc.ca/gov/content/data/statistics/people-population-community/population

| *Census Area*   | *Year* | *Count* |
|-----------------+--------+---------|
| Burnaby         |   2018 |   98789 |
| Coquitlam       |   2018 |   96700 |
| Maple Ridge     |   2018 |   43469 |
| New Westminster |   2018 |   35746 |
| Mission         |   2018 |   17627 |

Source: Prepared by BC Stats, Ministry of Technology, Innovation and Citizens' Services

* Land Use

Agricultural Land Reserve
https://www.alc.gov.bc.ca/alc/content/alr-maps/maps-and-gis


* Commuting


Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/

** Source 1 is 98-400-X2016324 - Main Mode of Commuting (10), Commuting Duration (7), Time Leaving for Work (7), Sex (3) and Age (5) for the Employed Labour Force Aged 15 Years and Over Having a Usual Place of Work or No Fixed Workplace Address

Huge amount of data here. Not sure the best way to visualize it. Here
is just the totals (e.g. significantly reduced dataset). There look to
be significant differences between men and womens commutes.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)
  src98.400.X2016324 <- function () {
      unz("../census2016/98-400-X2016324_ENG_CSV.ZIP", "98-400-X2016324_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016324(), header=T, nrow=1, quote="\"", sep=",")
  start <- 4553852 # Coquitlam Start
  end <- 4559102 # North Van Start
  df <- read.table(src98.400.X2016324(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              'Belcarra, VL',
              'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Sex..3., DIM..Age..5., DIM..Time.leaving.for.work..7., DIM..Main.mode.of.commuting..10.,
             Dim..Commuting.duration..7...Member.ID...1...Total...Commuting.duration,
             Dim..Commuting.duration..7...Member.ID...2...Less.than.15.minutes,
             Dim..Commuting.duration..7...Member.ID...3...15.to.29.minutes,
             Dim..Commuting.duration..7...Member.ID...4...30.to.44.minutes,
             Dim..Commuting.duration..7...Member.ID...5...45.to.59.minutes,
             Dim..Commuting.duration..7...Member.ID...6...60.minutes.and.over,
             Dim..Commuting.duration..7...Member.ID...7...Average.commuting.duration)

  names(df) <- c('city', 'sex', 'age', 'leave', 'mode', 'total.duration',
		 'lt15',
		 '15to29',
		 '30to44',
		 '45to59',
		 'gte60',
		 'avergae.duration')

  total <- df %>% filter(sex == 'Total - Sex', age == 'Total - Age')
  options(width=300)
  total
#+end_src

** Rest.



In the long form, there is information about journey to work.

98-400-X2016324 Mode, Duration, Exit Time, 
98-400-X2016328 Mode, Duration, Distance, Exit Time
98-400-X2016329 Destination, Mode   (Distination measures -- same census subdivision? same census division? same province?)
98-400-X2016334 Mode, Industry

I think if I sort of 'blend' the profiles for Vancouver and Mission/Abbotsford I can come up with some kind of reasonable guess.  This would have to be a slider.

'Assuming Tri-Cities are more like Vancouver --- More like Abbotsford'

https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/index-eng.cfm


He showed it as a commute distance chart... 
This data also varies with time... 2006 and 2016 we have.

They also showed a chart of commute modes.


| *City*         | *Carpool* | *Public Transit* | *Active Transit* | *Car* |
|----------------+-----------+------------------+------------------+-------|
| Coquitlam      |      12.4 |             17.9 |              4.3 |  65.4 |
| Port Moody     |      10.8 |             16.9 |              3.6 |  68.7 |
| Port Coquitlam |      13.2 |             12.6 |              3.7 |  70.5 |
| Anmore         |      10.8 |              7.7 |              1.4 |  80.1 |

| *City*         | *Avg Commute* |
|----------------+---------------|
| Coquitlam      |          33.8 |
| Port Moody     |            34 |
| Port Coquitlam |          32.6 |
| Anmore         |          32.5 |

* Housing types

Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/

You basically have to go there and search for the product name and download the data table as CSV.

** Source 1 is 98-400-X2016017 - Structural type by household size


# Output the table... Sort so the total is last.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)

  src98.400.X2016017 <- function () {
      unz("../census2016/98-400-X2016017_ENG_CSV.ZIP", "98-400-X2016017_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016017(), header=T, nrow=1, quote="\"", sep=",")
  start <- 43602 # Coquitlam Start
  end <- 43652 # North Van Start
  df <- read.table(src98.400.X2016017(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              'Belcarra, VL',
              'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Structural.type.of.dwelling..10.,
             Dim..Household.size..8...Member.ID...1...Total...Household.size,
             Dim..Household.size..8...Member.ID...2...1.person,
             Dim..Household.size..8...Member.ID...3...2.persons,
             Dim..Household.size..8...Member.ID...4...3.persons,
             Dim..Household.size..8...Member.ID...5...4.persons,
             Dim..Household.size..8...Member.ID...6...5.or.more.persons,
             Dim..Household.size..8...Member.ID...7...Number.of.persons.in.private.households,
             Dim..Household.size..8...Member.ID...8...Average.household.size)

  names(df) <- c('city', 'type', 'total.houses',
		 '1.person',
		 '2.persons',
		 '3.persons',
		 '4.persons',
		 '5.or.more.persons',
		 'total.persons',
		 'avergae.household.size')

  options(width=300)
  df
#+end_src

It looks like a lot of single family detached homes have just 1 or 2 people.

** Source 2 is 98-400-X2016015 - Structural type by age and sex.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)

  src98.400.X2016015 <- function () {
      unz("../census2016/98-400-X2016015_ENG_CSV.ZIP", "98-400-X2016015_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016015(), header=T, nrow=1, quote="\"", sep=",")
  start <- 130802 # Coquitlam Start
  end <- 130952 # North Van Start
  df <- read.table(src98.400.X2016015(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              'Belcarra, VL',
              'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities, DIM..Sex..3. == 'Total - Sex') %>%
      select(GEO_NAME, DIM..Structural.type.of.dwelling..10.,
             Dim..Age..20...Member.ID...1...Total...Age,
             Dim..Age..20...Member.ID...2...0.to.14.years,
             Dim..Age..20...Member.ID...3...15.to.19.years,
             Dim..Age..20...Member.ID...4...15.to.17.years,
             Dim..Age..20...Member.ID...5...18.to.19.years,
             Dim..Age..20...Member.ID...6...20.to.24.years,
             Dim..Age..20...Member.ID...7...25.to.29.years,
             Dim..Age..20...Member.ID...8...30.to.34.years,
             Dim..Age..20...Member.ID...9...35.to.39.years,
             Dim..Age..20...Member.ID...10...40.to.44.years,
             Dim..Age..20...Member.ID...11...45.to.49.years,
             Dim..Age..20...Member.ID...12...50.to.54.years,
             Dim..Age..20...Member.ID...13...55.to.59.years,
             Dim..Age..20...Member.ID...14...60.to.64.years,
             Dim..Age..20...Member.ID...15...65.years.and.over,
             Dim..Age..20...Member.ID...16...65.to.69.years,
             Dim..Age..20...Member.ID...17...70.to.74.years,
             Dim..Age..20...Member.ID...18...75.to.79.years,
             Dim..Age..20...Member.ID...19...80.to.84.years,
             Dim..Age..20...Member.ID...20...85.years.and.over)

  names(df) <- c('city', 'type',
		 'total',
		 '0.to.14',
		 '15.to.19',
		 '15.to.17',
		 '18.to.19',
		 '20.to.24',
		 '25.to.29',
		 '30.to.34',
		 '35.to.39',
		 '40.to.44',
		 '45.to.49',
		 '50.to.54',
		 '55.to.59',
		 '60.to.64',
		 '65.and.over',
		 '65.to.69',
		 '70.to.74',
		 '75.to.79',
		 '80.to.84',
		 '85.and.over')

  options(width=300)
  df
#+end_src

The total column doesn't always seem to add up to the other columns. I
dropped the 'sex' attribute, because men and women seemed about the
same.

All ages seem equally likely to be in a single-detached with a dip in
the 25 to 40 year old range. Maybe a trend, maybe affordability. They
seem to be more in apartments, or maybe duplexes.

* Heating and Electricity
Residential
Commercial Small/Medium
Large Industrial
Wholesale?

(For categories, Elec, Natural Gas, Heating Oil, Propane)

http://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/comprehensive_tables/list.cfm

* Solid Waste

They explained solid waste produced and the CO2 generated from that solid waste.

* Air Quality

They showed fine particulate matter.
