#+TITLE: The Problem

I think a story could be told around the scale of the
problem... breaking it down into the sub parts...

https://www.bcemissions.ca/go/city/Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Coquitlam/index.html
https://www.bcemissions.ca/go/city/Port_Moody/index.html

The above is a good starting point. Basically, I want to get the data
on the populations (because per-capita is important).

I also want to demonstrate land use, because this is the range of
options we have for local food, expansion, etc.

Then, breakdown into housing types.. because they have different energy profiles.
 - Should be able to get exact numbers for this.

Then, lets talk about the heating and electricity used... this varies with housing type.
 - I can really only get BC averages for this.  That's probably reasonable. I don't think
   any of the tri-cities is significantly better/worse efficiency ratings for houses than other places
   in BC.
 - This leads to an option for exploration -- what if we could change our housing profile?

Then, commutes... what type, how far.
 - Can't seem to get exact numbers -- have to let the user decide if we're more
   like Vancouver, or more like Mission.
 - This leads to an option -- what if we could increase the number of people living AND working in 
   tri-cities.... 

Then solid waste
  - CO2 produced... what about the cost of transporting it?  How much is compost and where does that go?
  - What about human body waste -- e.g. sewage... does this produce CO2?  What do we do with it at treatment?

Then air quality
  - How is our air?
  - What happens if we have more electric cars or walking?

* DONE Populations

** Source 1 is 98-400-X2016002 - Age (in Single Years) and Average Age (127) and Sex (3) for the Population of Canada, Census Metropolitan Areas, Census Agglomerations and Census Subdivisions, 2016 and 2011 Censuses - 100% Data 

#+begin_src R :session t :exports results :results table :colnames yes

  library(dplyr)
  src98.400.X2016002 <- function () {
      unz("../census2016/98-400-X2016002_ENG_CSV.ZIP", "98-400-X2016002_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016002(), header=T, nrow=1, quote="\"", sep=",")
  start <- 233682 # Coquitlam Start
  end <- 234952 # North Van Start
  df <- read.table(src98.400.X2016002(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  categories <- sapply(1:99, toString)
  categories[[length(categories)+1]] <- 'Under 1 year'
  categories[[length(categories)+1]] <- '100 years and over'

  df <- df %>%
      filter(GEO_NAME %in% cities, DIM..Age..in.single.years..and.average.age..127. %in% categories) %>%
      select(GEO_NAME,
             DIM..Age..in.single.years..and.average.age..127.,
             Dim..Sex..3...Member.ID...1...Total...Sex,
             Dim..Sex..3...Member.ID...2...Male,
             Dim..Sex..3...Member.ID...3...Female)

  names(df) <- c('city',
		 'age',
		 'total',
		 'male',
		 'female')

  df
#+end_src
* DONE Commuting

Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/

We can focus on switching people to different modes of transportation,
or we can focus on switching the distance they travel to work, or we
can focus on electrification of vehicles.

** Source 1 is 98-400-X2016324 - Main Mode of Commuting (10), Commuting Duration (7), Time Leaving for Work (7), Sex (3) and Age (5) for the Employed Labour Force Aged 15 Years and Over Having a Usual Place of Work or No Fixed Workplace Address

Huge amount of data here. Not sure the best way to visualize it. Here
is just the totals (e.g. significantly reduced dataset). There look to
be significant differences between men and womens commutes.

Seems about a 6:1 ratio of drivers to other forms of transportation.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)
  src98.400.X2016324 <- function () {
      unz("../census2016/98-400-X2016324_ENG_CSV.ZIP", "98-400-X2016324_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016324(), header=T, nrow=1, quote="\"", sep=",")
  start <- 4553852 # Coquitlam Start
  end <- 4559102 # North Van Start
  df <- read.table(src98.400.X2016324(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Sex..3., DIM..Age..5., DIM..Time.leaving.for.work..7., DIM..Main.mode.of.commuting..10.,
             Dim..Commuting.duration..7...Member.ID...1...Total...Commuting.duration,
             Dim..Commuting.duration..7...Member.ID...2...Less.than.15.minutes,
             Dim..Commuting.duration..7...Member.ID...3...15.to.29.minutes,
             Dim..Commuting.duration..7...Member.ID...4...30.to.44.minutes,
             Dim..Commuting.duration..7...Member.ID...5...45.to.59.minutes,
             Dim..Commuting.duration..7...Member.ID...6...60.minutes.and.over,
             Dim..Commuting.duration..7...Member.ID...7...Average.commuting.duration)

  names(df) <- c('city', 'sex', 'age', 'leave', 'mode', 'total.duration',
		 'lt15',
		 '15to29',
		 '30to44',
		 '45to59',
		 'gte60',
		 'avergae.duration')

  total <- df %>% filter(sex == 'Total - Sex', age == 'Total - Age')
  options(width=300)
  total
#+end_src

** Source 2 is 98-400-X2016334 - Main Mode of Commuting (10), Industry - North American Industry Classification System (NAICS) 2012 (21), Occupation - National Occupational Classification (NOC) 2016 (11) and Sex (3) for the Employed Labour Force Aged 15 Years and Over Having a Usual Place of Work or No Fixed Workplace Address, in Private Households of Canada, Provinces and Territories, Census Divisions and Census Subdivisions, 2016 Census - 25% Sample Data 

Most common jobs seem to be  in construction, retail, science, health, and education.

Driving alone is by far most common. Construction and health are like
1/6th transit. Retail is about 1/2 transit. Others about 1/3 transit.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)
  src98.400.X2016334 <- function () {
      unz("../census2016/98-400-X2016334_ENG_CSV.ZIP", "98-400-X2016334_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016334(), header=T, nrow=1, quote="\"", sep=",")
  start <- 3005543 # Coquitlam Start
  end <- 3009008 # North Van Start
  df <- read.table(src98.400.X2016334(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Sex..3.,
             DIM..Occupation...National.Occupational.Classification..NOC..2016..11.,
             DIM..Industry...North.American.Industry.Classification.System..NAICS..2012..21.,
             Dim..Main.mode.of.commuting..10...Member.ID...1...Total...Main.mode.of.commuting..Note..3.,
             Dim..Main.mode.of.commuting..10...Member.ID...2...Car..truck.or.van,
             Dim..Main.mode.of.commuting..10...Member.ID...3...Driver..alone,
             Dim..Main.mode.of.commuting..10...Member.ID...4...2.or.more.persons.shared.the.ride.to.work,
             Dim..Main.mode.of.commuting..10...Member.ID...5...Driver..with.1.or.more.passengers,
             Dim..Main.mode.of.commuting..10...Member.ID...6...Passenger..2.or.more.persons.in.the.vehicle,
             Dim..Main.mode.of.commuting..10...Member.ID...7...Sustainable.transportation,
             Dim..Main.mode.of.commuting..10...Member.ID...8...Public.transit,
             Dim..Main.mode.of.commuting..10...Member.ID...9...Active.transport,
             Dim..Main.mode.of.commuting..10...Member.ID...10...Other.method)

  names(df) <- c('city', 'sex', 'NOC', 'NAICS', 'mode.total',
		 'Car..truck.or.van',
		 'Driver..alone',
		 '2.or.more.persons.shared.the.ride.to.work',
		 'Driver..with.1.or.more.passengers',
		 'Passenger..2.or.more.persons.in.the.vehicle',
		 'Sustainable.transportation',
		 'Public.transit',
		 'Active.transport',
		 'Other')

  total <- df %>% filter(sex == 'Total - Sex', NOC == 'Total - Occupation - National Occupational Classification (NOC) 2016')
  options(width=300)
  total
#+end_src

** Source 3 is 98-400-X2016328 - Main Mode of Commuting (10), Commuting Duration (6), Distance from Home to Work (12) and Time Leaving for Work (7) for the Employed Labour Force Aged 15 Years and Over Having a Usual Place of Work, in Private Households of Canada, Provinces and Territories, Census Divisions and Census Subdivisions, 2016 Census - 25% Sample Data 

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)
  src98.400.X2016328 <- function () {
      unz("../census2016/98-400-X2016328_ENG_CSV.ZIP", "98-400-X2016328_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016328(), header=T, nrow=1, quote="\"", sep=",")
  start <- 1821542 # Coquitlam Start
  end <- 1823642 # North Van Start
  df <- read.table(src98.400.X2016328(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME,
             DIM..Commuting.duration..6.,
             DIM..Time.leaving.for.work..7.,
             DIM..Main.mode.of.commuting..10.,
             Dim..Distance.from.home.to.work..12...Member.ID...1...Total...Distance.from.home.to.work..Note..2.,
             Dim..Distance.from.home.to.work..12...Member.ID...2...Less.than.1.km,
             Dim..Distance.from.home.to.work..12...Member.ID...3...1.to.2.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...4...3.to.4.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...5...5.to.6.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...6...7.to.9.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...7...10.to.14.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...8...15.to.19.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...9...20.to.24.9.Km,
             Dim..Distance.from.home.to.work..12...Member.ID...10...25.to.29.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...11...30.to.34.9.km,
             Dim..Distance.from.home.to.work..12...Member.ID...12...35.km.or.more)

  names(df) <- c('city', 'dur', 'exit.time', 'mode',
		 'total.dist',
		 'Less.than.1.km',
		 '1.to.2.9.km',
		 '3.to.4.9.km',
		 '5.to.6.9.km',
		 '7.to.9.9.km',
		 '10.to.14.9.km',
		 '15.to.19.9.km',
		 '20.to.24.9.km',
		 '25.to.29.9.km',
		 '30.to.34.9.km',
		 '35.km.or.more')

  total <- df %>% select(-exit.time) %>% group_by(city, mode) %>% summarize_each(sum, `total.dist`, `Less.than.1.km`, `1.to.2.9.km`, `3.to.4.9.km`, `5.to.6.9.km`, `7.to.9.9.km`, `10.to.14.9.km`, `15.to.19.9.km`, `20.to.24.9.Km`, `25.to.29.9.km`, `30.to.34.9.km`, `35.km.or.more`)

  options(width=300)
  total
#+end_src

** Source 4 is 98-400-X2016329 - Commuting Destination (5), Main Mode of Commuting (10), Sex (3) and Age (5) for the Employed Labour Force Aged 15 Years and Over Having a Usual Place of Work, in Private Households of Canada, Provinces and Territories, Census Divisions and Census Subdivisions, 2016 Census - 25% Sample Data

#+begin_src R :session t :exports results :results table :colnames yes

  library(dplyr)
  src98.400.X2016329 <- function () {
      unz("../census2016/98-400-X2016329_ENG_CSV.ZIP", "98-400-X2016329_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016329(), header=T, nrow=1, quote="\"", sep=",")
  start <- 650552 # Coquitlam Start
  end <- 651302 # North Van Start
  df <- read.table(src98.400.X2016329(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam',
              ## 'Belcarra',
              ## 'Anmore',
              'Port Coquitlam',
              'Port Moody')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME,
             DIM..Sex..3.,
             DIM..Age..5.,
             DIM..Main.mode.of.commuting..10.,
             Dim..Commuting.destination..5...Member.ID...1...Total...Commuting.destination,
             Dim..Commuting.destination..5...Member.ID...2...Commute.within.census.subdivision..CSD..of.residence,
             Dim..Commuting.destination..5...Member.ID...3...Commute.to.a.different.census.subdivision..CSD..within.census.division..CD..of.residence,
             Dim..Commuting.destination..5...Member.ID...4...Commute.to.a.different.census.subdivision..CSD..and.census.division..CD..within.province.or.territory.of.residence,
             Dim..Commuting.destination..5...Member.ID...5...Commute.to.a.different.province.or.territory)

  names(df) <- c('city',
		 'sex',
		 'age',
		 'mode',
		 'total',
		 'within_subdivision',
		 'within_census_division',
		 'within_province',
		 'other_province')

  total <- df %>% filter(sex == 'Total - Sex', age == 'Total - Age')
  options(width=300)
  total
#+end_src

* DONE Housing types

Best source is here. 2016 Census data:

https://www12.statcan.gc.ca/

You basically have to go there and search for the product name and download the data table as CSV.

** Source 1 is 98-400-X2016017 - Structural type by household size


# Output the table... Sort so the total is last.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)

  src98.400.X2016017 <- function () {
      unz("../census2016/98-400-X2016017_ENG_CSV.ZIP", "98-400-X2016017_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016017(), header=T, nrow=1, quote="\"", sep=",")
  start <- 43602 # Coquitlam Start
  end <- 43652 # North Van Start
  df <- read.table(src98.400.X2016017(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities) %>%
      select(GEO_NAME, DIM..Structural.type.of.dwelling..10.,
             Dim..Household.size..8...Member.ID...1...Total...Household.size,
             Dim..Household.size..8...Member.ID...2...1.person,
             Dim..Household.size..8...Member.ID...3...2.persons,
             Dim..Household.size..8...Member.ID...4...3.persons,
             Dim..Household.size..8...Member.ID...5...4.persons,
             Dim..Household.size..8...Member.ID...6...5.or.more.persons,
             Dim..Household.size..8...Member.ID...7...Number.of.persons.in.private.households,
             Dim..Household.size..8...Member.ID...8...Average.household.size)

  names(df) <- c('city', 'type', 'total.houses',
		 '1.person',
		 '2.persons',
		 '3.persons',
		 '4.persons',
		 '5.or.more.persons',
		 'total.persons',
		 'avergae.household.size')

  options(width=300)
  df
#+end_src

It looks like a lot of single family detached homes have just 1 or 2 people.

** Source 2 is 98-400-X2016015 - Structural type by age and sex.

#+begin_src R :session t :exports results :results table :colnames yes
  library(dplyr)

  src98.400.X2016015 <- function () {
      unz("../census2016/98-400-X2016015_ENG_CSV.ZIP", "98-400-X2016015_English_CSV_data.csv")
  }

  df.row1 <- read.table(src98.400.X2016015(), header=T, nrow=1, quote="\"", sep=",")
  start <- 130802 # Coquitlam Start
  end <- 130952 # North Van Start
  df <- read.table(src98.400.X2016015(), col.names = names(df.row1), skip = start, nrow = end - start - 1, quote="\"", sep=",")

  cities <- c('Coquitlam, CY',
              ## 'Belcarra, VL',
              ## 'Anmore, VL',
              'Port Coquitlam, CY',
              'Port Moody, CY')

  df <- df %>%
      filter(GEO_NAME %in% cities, DIM..Sex..3. == 'Total - Sex') %>%
      select(GEO_NAME, DIM..Structural.type.of.dwelling..10.,
             Dim..Age..20...Member.ID...1...Total...Age,
             Dim..Age..20...Member.ID...2...0.to.14.years,
             Dim..Age..20...Member.ID...3...15.to.19.years,
             Dim..Age..20...Member.ID...4...15.to.17.years,
             Dim..Age..20...Member.ID...5...18.to.19.years,
             Dim..Age..20...Member.ID...6...20.to.24.years,
             Dim..Age..20...Member.ID...7...25.to.29.years,
             Dim..Age..20...Member.ID...8...30.to.34.years,
             Dim..Age..20...Member.ID...9...35.to.39.years,
             Dim..Age..20...Member.ID...10...40.to.44.years,
             Dim..Age..20...Member.ID...11...45.to.49.years,
             Dim..Age..20...Member.ID...12...50.to.54.years,
             Dim..Age..20...Member.ID...13...55.to.59.years,
             Dim..Age..20...Member.ID...14...60.to.64.years,
             Dim..Age..20...Member.ID...15...65.years.and.over,
             Dim..Age..20...Member.ID...16...65.to.69.years,
             Dim..Age..20...Member.ID...17...70.to.74.years,
             Dim..Age..20...Member.ID...18...75.to.79.years,
             Dim..Age..20...Member.ID...19...80.to.84.years,
             Dim..Age..20...Member.ID...20...85.years.and.over)

  names(df) <- c('city', 'type',
		 'total',
		 '0.to.14',
		 '15.to.19',
		 '15.to.17',
		 '18.to.19',
		 '20.to.24',
		 '25.to.29',
		 '30.to.34',
		 '35.to.39',
		 '40.to.44',
		 '45.to.49',
		 '50.to.54',
		 '55.to.59',
		 '60.to.64',
		 '65.and.over',
		 '65.to.69',
		 '70.to.74',
		 '75.to.79',
		 '80.to.84',
		 '85.and.over')

  options(width=300)
  df
#+end_src

The total column doesn't always seem to add up to the other columns. I
dropped the 'sex' attribute, because men and women seemed about the
same.

All ages seem equally likely to be in a single-detached with a dip in
the 25 to 40 year old range. Maybe a trend, maybe affordability. They
seem to be more in apartments, or maybe duplexes.

* Land Use

Agricultural Land Reserve
https://www.alc.gov.bc.ca/alc/content/alr-maps/maps-and-gis

* Heating and Electricity
Residential
Commercial Small/Medium
Large Industrial
Wholesale?

(For categories, Elec, Natural Gas, Heating Oil, Propane)

http://oee.nrcan.gc.ca/corporate/statistics/neud/dpa/menus/trends/comprehensive_tables/list.cfm

* Solid Waste

They explained solid waste produced and the CO2 generated from that solid waste.

* Air Quality

They showed fine particulate matter.
