#+TITLE: Requirements

* What Goes into this Plan?

A vision for the next many years.

 - Integrating the City to reduce driving
 - A transit plan
 - Energy efficiency measures
 - Zoning changes to encourage densification
 - Green Spaces and stuff like that
 - Ammenities, social housing, etc,
 - Resilency via local committee efforts.
 - ELECTRIFIED CITY FLEET (They spend 3,870,000 per year on fleet capital).

More ideas:

 - Tech incubator for green tech (e.g. mist showers)
 - Living wage regulation -- so Coq businesses must pay at least enough so that there
   workers can afford the live in Coq?
 - Buyback of abandoned homes. Convert to neighborhood green spaces.
   (About $12 million a year is spent buying parklands... so that's like twelve houses ;-)
   But why should some private individual make a million dollars on an abandoned home?
 - Covered side walks (e.g. by trees) wider sidewalks.
   (Bicycle/Greenway Facilities Program in Coquitlam?)
 - Zoning changes.
 - Promoting eat local, buy local?
 - Raise money via 'Bonds' -- city debt owned to city citizens and repayed to them,
   rather than to banks.
 - Why are libraries public but gyms private?  Why are roads public
   but telecommunications private?  Why are buses public but taxis
   private?

Civic facilities are expensive... are they necessary? Is there a small
sort of thing that could be done?  Like turning houses into libraries?
Or library depots or something?
