#+TITLE: Urban Food

https://www.sustainweb.org/publications/growing_food_in_cities_the_benefits/

Is there a food tradeoff?  I've seen from books that you can grow food
in a high-intensity kind of way. An Acre feeding 26 families (but not
enough... lets say 10 people to acre).  A rough ballpark (John Jevins
method) says we can do 8 people on an Acre... so two households.  But
an Acre takes maybe the space of 20 homes. So to get this food, these
two households would need to pay the tax equivalent of 20 * 2400 which
is $2,000 a month and not feasible.

We can't be growing food inside city limits... but what land do we
control?  Could we go back to having nearby farmland and reduce food
miles?

Another question -- can we compost near the cities and eliminate most
garbage fees? It's basically $35 a month for garbage.  If people took
their garbage to a neighborhood compost pile, and that was sold on to
farms, could we eliminate this fee?  Note that this is what the
compost trucks do -- but they go all the way to Delta, where the
farmland is.  Could the farms be closer to eliminate fuel usage?
Combine this with park space? 

At the very least, can we grow food trees in cities?  If we drove electric,
then the fruit wouldn't be poisoned by the roads.  Public apple orchards?
